import Head from 'next/head';
import Sidebar from '../src/components/Sidebar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by ng-ha" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Sidebar />
      </main>
    </>
  );
}
